### ISSUE TITLE
Use fluff python API rather than CLI

### ISSUE THREAD

**Issue by nolanbconaway** [sqlfluff/sqlfluff-online#14]
No reason to get subprocess in the mix here.

**Comment by alanmcruickshank** [comment]
I've just been working on doing a bit more segregation to make something like this a bit easier: https://github.com/sqlfluff/sqlfluff/pull/460

I'd love to approach this issue as an excuse to firm up what the "public API" of SQLfluff should be and how people should use it. It's quite undocumented at the moment, and the only real existing use case (other than the sqlfluff cli itself `sqlfluff.cli`) is the [diff quality plugin](https://github.com/sqlfluff/sqlfluff/blob/master/src/sqlfluff/diff_quality_plugin.py).

The solution to that is likely a mix of better docs, and also firming up which bits of sqlfluff we expect people to import and which bits not. If you have a go at this issue, I'd love your feedback for what needs to improve on the sqlfluff side to facilitate this (or other things like this 😄 ).

**Comment by nolanbconaway** [comment]
Thank goodness, the parsing / logging connection had been driving me _nuts_ 😓  ! 

My view is that the public python api could be as little as two functions, `lint()` and `fix()`, which take in the exact same arguments as the CLI and spit out the same data (except in the case of lint, which should produce a dict instead of string).

When I get around to this, I'll end up implementing those functions but probably without complex config handling. In any case someone who knows the code base more (you, @alanmcruickshank ?) could probably easily shift what i've got into a public api.

**Comment by alanmcruickshank** [comment]
I'm quite keen to stay close to the initial iteration of the public API so that we do it really well. That also means I don't mind taking on a load of the dev work to make it happen.

> My view is that the public python api could be as little as two functions, lint() and fix(), which take in the exact same arguments as the CLI and spit out the same data (except in the case of lint, which should produce a dict instead of string).

So that I've got an idea of roughly what you mean, would you be able to write out a few rough pseudocode style examples of how you'd expect to import and use sqlfluff? My best interpretation of what you've said so far would be something like:

```
import sqlfluff

my_bad_query = "SeLEct  *, 1, blah as  fOO  from myTable"
linted_result = sqlfluff.lint(my_bad_query, dialect='bigquery')
for violation in linted_result.violations:
   print(violation.as_string())
```

And you'd get an output like:

```
L:   1 | P:   1 | L010 | Inconsistent capitalisation of keywords.
L:   1 | P:  12 | L013 | Column expression without alias. Use explicit `AS`
                       | clause.
L:   1 | P:  24 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:   1 | P:  34 | L009 | Files must end with a trailing newline.
L:   1 | P:  34 | L014 | Inconsistent capitalisation of unquoted identifiers.
```

If you're able to put together a couple of small "potted" examples like this, then I think we'll be able to pick through a couple of the design decisions and get something that doesn't just work, but also feels nice to use as a developer.

**Comment by nolanbconaway** [comment]
+1 on you taking the lead for implementation; completely agree that this should be done _right_ and I don't know my way around anything but the CLI.

Your example looks right to me! In your view would this API also support the CLI? The reason I ask is that I wonder what people would want of `linted_result` besides the violations. The most basic use case IMO is using `lint` to produce a list of violation objects, but obviously the function needs to support a lot more for the CLI.

Here is some pseudocode that i would be thinking about independently of your example:

```py
import sqlfluff

#  -------- LINTING ----------

my_bad_query = "SeLEct  *, 1, blah as  fOO  from myTable"

# very easy to JSON dump!
sqlfluff.lint(my_bad_query, dialect="bigquery")

[
    {'line': 1, 'position':  1, 'violation': 'L010', 'message': 'Inconsistent capitalisation of keywords'},
    {'line': 1, 'position': 12, 'violation': 'L013', 'message': 'Column expression without alias. Use explicit `AS` clause'},
    {'line': 1, 'position': 24, 'violation': 'L014', 'message': 'Inconsistent capitalisation of unquoted identifiers'},
    {'line': 1, 'position': 34, 'violation': 'L009', 'message': 'Files must end with a trailing newline'},
    {'line': 1, 'position': 34, 'violation': 'L014', 'message': 'Inconsistent capitalisation of unquoted identifiers'},
]

#  -------- FIXING ----------

sqlfluff.fix(my_bad_query, dialect="bigquery")

'SELECT  *, 1, blah AS  foo  FROM mytable'
```

**Comment by mrshu** [comment]
@nolanbconaway Do think think this is something that could be reasonably implemented now?

**Comment by nolanbconaway** [comment]
Yep! as soon as 0.4.0 is launched i plan on implementing for this ticket!

**Comment by mrshu** [comment]
Cool, thanks @nolanbconaway  -- do let me know if I can be of some help!
