### ISSUE TITLE
`sqlfluffOnline` Input Textbox is broken

### ISSUE THREAD

**Issue by daniel-anya** [sqlfluff/sqlfluff-online#141]
As of Aug 3, 2022 7:00pm UTC, the input textbox on https://online.sqlfluff.com/ is not working. Users are not able to paste queries to be formatted. 

It looks like the this issue is caused by the `https://pagecdn.io/lib/ace/1.4.12/ace.js` dependency. Currently, the browser console shows a 404 response for a request to get this resource.

**Comment by nolanbconaway** [comment]
Uhoh! ill look into this.

**Comment by daniel-anya** [comment]
Opened a PR to fix it here - https://github.com/sqlfluff/sqlfluff-online/pull/142

**Comment by nolanbconaway** [comment]
Thanks!!
