### ISSUE TITLE
systemd service file

### ISSUE THREAD

**Issue by jgarte** [sqlfluff/sqlfluff-online#41]
Hi, would you be able to share the systemd service file that runs on https://online.sqlfluff.com/ ?

The reason I ask is because I'm working on packaging `sqlfluff` for [GNU Guix](guix.gnu.org) and would like to eventually use that service file as a reference for creating the service file for Guix System.

**Comment by nolanbconaway** [comment]
Do you have anything like this @alanmcruickshank ? I definitely did not set up any systemd for deployment

**Comment by jgarte** [comment]
> Do you have anything like this @alanmcruickshank ? I definitely did not set up any systemd for deployment

Hi! 

Or, did you set up sqlfluff in some other way when deploying?

Maybe the question I should of asked is:

How do you deploy the current live instance of sqlfluff?

**Comment by nolanbconaway** [comment]
Oh! Its set up on google app engine !
