### ISSUE TITLE
alias for subquery shouldn't be omitted even if not used

### ISSUE THREAD

**Issue by benshlomogal** [sqlfluff/sqlfluff-online#61]
Hi and thanks for this project!

when formatting a query that has a subquery with an alias - the alias gets omitted when it isn't explicitly used in the select statement, Though this would cause a failure in all databased that I worked with.

example (I chose Postgres dialect):
```SQL
select *
  from (
       select *
         from table
       ) a
```
output:
```SQL
select *
from (
        select *
         from table
    )
```

**Comment by WittierDinosaur** [comment]
Can you raise this in repo for the main project? https://github.com/sqlfluff/sqlfluff/issues
